### ISSUE TITLE
Unable to get console log messages

### ISSUE THREAD

**Issue by tspiva** [adieuadieu/serverless-chrome#121]
I'm using the `chrome-remote-interface` to grab screenshots.  As things go on, I would like to be able to write console.log (warn, error) to the console log and be able to see them in my project.

I'm currently using the `Runtime` (and `Runtime.enable()` and `Runtime.consoleAPICalled(msg => {} ).  This is working beautifully on a mac, but when I try to run it in lambda I don't get any console log messages.

In my serverless config I specify:
```
custom:
  chrome:
    flags:
      - --window-size=1280x1696 # Letter size
      - --hide-scrollbars
      - --verbose
      - --enable-logging
      - --log-level=0
```
and I have the environment variable `DEBUG=*` set.  

Anyone have any idea what else I can try?
