### ISSUE TITLE
serverless invoke local -f with serverless-plugin-typescript

### ISSUE THREAD

**Issue by ecwyne** [adieuadieu/serverless-chrome#152]
```yml
service: my-service

plugins:
    - serverless-plugin-typescript
    - serverless-plugin-chrome

provider:
    stage: prod
    name: aws

functions:
    funcA:
        handler: src/funcA.handler
    funcB:
        handler: src/funcB.handler
```

If I run `serverless invoke local -f funcA` it appears that `serverless-plugin-typescript` only transpiles `funcA` so there is no `funcB` to inject Headless Chrome into.

```
ENOENT: no such file or directory, link '/my-service/.build/src/funcB.js' -> '/my-service/.build/src/k4w2e96cu3a___funcB.js'
```

When being invoked locally `serverless-plugin-chrome` should only "inject" into the invoked function (and no others)
