### ISSUE TITLE
Plugin not working with serverless-plugin-warmup

### ISSUE THREAD

**Issue by fantapop** [adieuadieu/serverless-chrome#160]
We use https://github.com/FidelLimited/serverless-plugin-warmup in order to make sure there's always at least one lambda container spun up.  This plugin creates an additional lambda which calls all other lambdas in serverless config.   When serverless-plugin-chrome plug is included, deployment fails.  

```
Serverless: WarmUP: setting 1 lambdas to be warm
Serverless: WarmUP: page-renderer-devint-renderThumbnail
Serverless: Injecting Headless Chrome...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...

  Error --------------------------------------------------

  ENOENT: no such file or directory, open '/Users/chris/Development/page-renderer/.build/.serverless/warmUpPlugin.zip'
```

I've watched this directory ```.build/.serverless/``` and the warmUpPlugin.zip files is built and exists before the other lambdas but then all these disappear and this failure appears. 

I noticed serverless-chrome is messing around with these files.  Could this be causing the breakage?
https://github.com/adieuadieu/serverless-chrome/blob/master/packages/serverless-plugin/src/index.js#L193

**Comment by fantapop** [comment]
I'm seeing some really strange behavior while trying to take a screenshot.  It seems likely that its lower level than this project but i wanted to explain why I'm interested in using warmup.  Whenever a new lambda container spins up, the call I'm making to Page.captureScreenshot just hangs.   I'm setting a timeout and retrying the entire rendering on failure.  It usually takes around 80 seconds of retrying every 10 seconds to get the screenshot to take.  After this, it works instantly every time that container is invoked.  It appears that killing the chrome instance after each invocation is also causing this hanging behavior.    My hope was that if I could keep the lambda container warm I could avoid this initial timeout duration.

**Comment by adieuadieu** [comment]
Hm.. About the incompatibility with the `serverless-warmup-plugin`.. I have two workarounds for you:

1. Don't use the `serverless-plugin-chrome`, and instead use the `@serverless-chrome/lambda` package directly. This means that you'll then have to start chrome in your own code.
1. Don't use the `serverless-warmpup-plugin`, and instead add a [cloudwatch "schedule" event](https://serverless.com/framework/docs/providers/aws/events/schedule/) to your lambda functions triggers. For example, in your `serverless.yml` file:

```yml
functions:
  chromeHandler:
    handler: path/to/your/handler.js
    events:
      - schedule:
          name: keep-chromeHandler-warm
          description: Keeps the lambda function warm by invoking it on a schedule
          rate: rate(5 minutes)
      - ... your other trigger events here
```
