### ISSUE TITLE
Couldn't load http content

### ISSUE THREAD

**Issue by kikouch** [adieuadieu/serverless-chrome#207]
Hello teams, 

I have a page that requests http in lambda yet it couldn't load properly. I tried adding 
'- --allow-running-insecure-content' to serverless.yml but still doesn't working.

```
custom:
  chrome:
    flags:
      - --window-size=1280,1696 # Letter size
      - --hide-scrollbars
      - --allow-running-insecure-content
```

I'm following this example
https://github.com/adieuadieu/serverless-chrome/tree/master/examples/serverless-framework/aws

If you know any configuration, please let me know, thanks

Ref
https://github.com/adieuadieu/serverless-chrome/tree/master/packages/serverless-plugin#configuration
https://peter.sh/experiments/chromium-command-line-switches/#allow-running-insecure-content

P.S
I found this qoute
`The behavior of Chrome does vary between platforms. It may be necessary to experiment with flags to get the results you desire. On Lambda default flags are used, but in development no default flags are used.`
Does it mean that we can't config flags in lambda?
