### ISSUE TITLE
Path argument must be type of string, with serverless-chrome@1.0.0-55.1

### ISSUE THREAD

**Issue by serverlessguru** [adieuadieu/serverless-chrome#245]
serverless.yml
```
org: org-name
app: app-name
service: service-name
provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "dev"}
  profile: ${opt:profile, "default"}
  timeout: 30

plugins:
  - serverless-plugin-chrome

custom:
  # Chrome plugin settings
  chrome:
    flags:
      - --window-size=1280,1696
      - --hide-scrollbars
      - --headless
      - --no-sandbox
    functions:
      - funA
      - funB
  
functions:
  funA:
    ...

  funB:
    ...
```
deploy command
```
sls deploy
```
error
```
> sls deploy --region us-east-1 -v

Serverless: Injecting Headless Chrome...
 
  Type Error ---------------------------------------------
 
  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
      at validateString (internal/validators.js:107:11)
      at Object.path [as resolve] (path.js:978:7)
      at ../node_modules/serverless-plugin-chrome/src/index.js:175:52
```

Another note, if I don't want the plugin to autowrap my code, are there any alternatives?
