### ISSUE TITLE
Return binary

### ISSUE THREAD

**Issue by willfarrell** [adieuadieu/serverless-chrome#36]
In your comments you mention `it's not possible to send binary via AWS API Gateway as it expects JSON response from Lambda`. You can do it with:

serverless.yml
```yml
plugins:
  - serverless-apigwy-binary # <-- Add
...
functions:
  run:
    description: Run headless Chromium
    memorySize: 1536
    timeout: 30
    handler: handler.run

    events:
      - http:
          path: chrome
          method: get
          contentHandling: CONVERT_TO_BINARY. # <-- Add
```

handler:
```js
{
                        statusCode: 200,
                        isBase64Encoded: true,  // <-- Add
                        body: screenshot.toString('base64')
}
```

I'm working on a PR right now.
