### ISSUE TITLE
Plugin: Wrap only necessary functions

### ISSUE THREAD

**Issue by adieuadieu** [adieuadieu/serverless-chrome#47]
Implement this behavior: if `custom.chromeSomething` is undefined... Then all functions get the wrapper. If it's an array with function names, then limit it to just those functions listed by name in the array.

enable the chrome injection on a per function basis

```yaml
custom:
  chrome:
    - myFancyChromeFunction
    - anotherReallyCoolChromeFunction
```
