### ISSUE TITLE
serverless-plugin: ECONNREFUSED

### ISSUE THREAD

**Issue by davewingate** [adieuadieu/serverless-chrome#63]
@adieuadieu Thanks for starting such an awesome project.  I'm trying to follow the [README for the project's serverless plugin](https://github.com/adieuadieu/serverless-chrome/blob/develop/packages/serverless-plugin/README.md), but found that the steps documented did not work for me.

Here's what I've tried.

package.json
```
{
  "name": "serverless-chrome-plugin",
  "version": "0.0.1",
  "description": "hello, does it work?",
  "main": "index.js",
  "scripts": {
    "deploy": "serverless deploy -v"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "chrome-remote-interface": "0.24.5"
  },
  "devDependencies": {
    "serverless": "1.21.0",
    "serverless-plugin-chrome": "1.0.0-11"
  }
}
```

serverless.yml
```
service: hello-serverless-chrome-plugin

frameworkVersion: "1.21.0"
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  stage: dev
  profile: lithiumdev 

plugins:
  - serverless-plugin-chrome

functions:
  hello:
    handler: handler.hello
    description: try out this ol' lambda thing
    memorySize: 1536
    timeout: 60

    events:
      - http:
          path: hello
          method: get
```

handler.js
```
const CDP = require('chrome-remote-interface')

module.exports.hello = (event, context, callback, chrome) => {
  // Chrome is already running!

  CDP.Version()
    .then((versionInfo) => {
      callback(null, {
        statusCode: 200,
        body: JSON.stringify({
          versionInfo,
          chrome,
        }),
      })
    })
    .catch((error) => {
      callback(null, {
        statusCode: 500,
        body: JSON.stringify({
          error,
        }),
      })
    })
}
```

When I invoke on lambda, I get this response:
```{"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":9222}}```

I'm a bit new to both node and CDP.  I was wondering, could you suggest what might be going wrong?
